# Generated by Django 5.0.7 on 2024-07-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=200)),
                ('descricao_do_produto', models.TextField()),
                ('imagem_produto', models.ImageField(upload_to='produtos/')),
                ('preco_do_produto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
