# Generated by Django 5.0.7 on 2024-07-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_principal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='descricao_do_produto',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='preco_do_produto',
            new_name='preco',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='nome_produto',
        ),
        migrations.AddField(
            model_name='produto',
            name='nome',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
