# Generated by Django 5.0.7 on 2024-07-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_principal', '0002_rename_descricao_do_produto_produto_descricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('produto', models.ManyToManyField(related_name='Categorias', to='sistema_principal.produto')),
            ],
        ),
    ]
