# Generated by Django 5.0.7 on 2024-07-23 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_principal', '0003_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='produto',
        ),
        migrations.AddField(
            model_name='categoria',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sistema_principal.produto'),
            preserve_default=False,
        ),
    ]
