# Generated by Django 5.0.7 on 2024-07-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_principal', '0004_remove_categoria_produto_categoria_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='produto',
        ),
        migrations.AddField(
            model_name='categoria',
            name='produtos',
            field=models.ManyToManyField(related_name='categorias', to='sistema_principal.produto'),
        ),
    ]
