# Generated by Django 5.0.7 on 2024-07-23 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_principal', '0005_remove_categoria_produto_categoria_produtos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='produtos',
        ),
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='sistema_principal.categoria'),
            preserve_default=False,
        ),
    ]
