# Generated by Django 5.0.7 on 2024-07-23 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_principal', '0006_remove_categoria_produtos_categoria_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='slug',
        ),
    ]
