# Generated by Django 5.0.7 on 2024-07-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_principal', '0009_remove_produto_categoria_categoria_produtos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='produtos',
        ),
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
