# Generated by Django 5.0.7 on 2024-07-23 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_principal', '0011_remove_categoria_slug_subcategoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategoria',
        ),
    ]
