# Generated by Django 5.0.7 on 2024-07-24 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_principal', '0014_remove_subcategoria_categoria_produto_desconto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='sistema_principal.categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade_de_produtos',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
