# Generated by Django 5.0.7 on 2024-07-24 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_principal', '0016_imagemproduto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem_produto',
        ),
    ]
