# Generated by Django 5.0.7 on 2024-07-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_principal', '0017_remove_produto_imagem_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('produtos', models.ManyToManyField(related_name='promocoes', to='sistema_principal.produto')),
            ],
        ),
    ]
