# Generated by Django 5.0.7 on 2024-07-30 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_principal', '0018_promocao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='valor_frete',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
