# Generated by Django 5.0.7 on 2024-08-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_principal', '0023_alter_itemcarrinho_id_alter_itemcarrinho_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcarrinho',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='itemcarrinho',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
    ]
