# Generated by Django 5.0.7 on 2024-08-03 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_principal', '0024_alter_itemcarrinho_id_alter_itemcarrinho_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcarrinho',
            name='carrinho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema_principal.carrinho'),
        ),
    ]
