# Generated by Django 5.0.7 on 2024-08-03 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_principal', '0025_alter_itemcarrinho_carrinho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcarrinho',
            name='carrinho',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sistema_principal.carrinho'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('em_processamento', 'Em processamento'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='em_processamento', max_length=50),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade_de_produtos',
            field=models.IntegerField(),
        ),
    ]
